name = "MatrixAlgebra"
uuid = "25f3c6f7-e090-4425-b6b3-5ee689bc77e8"
authors = ["Klaus Crusius <klaus.crusius@web.de>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"

[targets]
test = ["Test", "BandedMatrices"]
